version: '3'

services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: marlonlacerda2/node
    container_name: ngnix
    ports: 
      - "1234:80"
    networks:
      - production-network
    
    depends_on:
     - "node1"
     - "node2"
     - "node3"



  mongo:
    image: mongo
    networks:
      - production-network     

  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: marlonlacerda2/node
    container_name: node1
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongo"

  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: marlonlacerda2/node
    container_name: node2
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongo"
  

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: marlonlacerda2/node
    container_name: node3
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongo"




networks:
  production-network:
    driver : bridge
